version: '3.8'

services:
  vromvrom-engine:
    build: .
    container_name: vromvrom-engine
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
